nome: 'Define Variables'
description: 'Define as variáveis necessárias para o workflow do projeto.'

inputs:
  ACR:
    description: 'Valor do ACR'
    default: 'braspagxpto'


runs:
  using: composite

  steps:
    - name: define variables
      id: define-variables
      shell: bash
      run: |
        echo "----------- Test Define Variables Composite -------------"
        echo "${{ inputs.ACR }}"
        echo "Detectado Branch --> ${{ github.ref_name }}"
        if [[ "${{ inputs.ACR }}" == 'xpto' && ${{ github.ref_name}} == 'main' ]]; then
          echo "Detectado ACR Cielo."
          echo "Definido ACR de PRD!"
          ACR_NAME=acrproduction
          echo "VALOR ------> $ACR_NAME"
          echo "ACR_NAME=acrproduction" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.ACR }}" == 'xpto' && "${{ github.ref_name }}" == 'develop' || "${{ github.ref_name }}" == 'release' ]]; then
          echo "Detectado ACR Cielo."
          echo "Definido ACR de DEV/HML!"
          echo "ACR_NAME=acrdevhml" >> $GITHUB_OUTPUT
        else
          echo "Detectado ACR Braspag."
          echo "${{ inputs.ACR }}"
          echo "ACR_NAME=${{ inputs.ACR }}" >> $GITHUB_OUTPUT
        fi