nome: 'Define Variables'
description: 'Define as variáveis necessárias para o workflow do projeto.'

inputs:
  ACR_NAME:
    description: 'Nome do ACR de destino.'
    required: false
    default: 'braspagxpto'

outputs:
  ACR_NAME:
    description: 'Nome do ACR.'
    value: ${{ steps.define-variables.outputs.ACR_NAME }}

runs:
  using: composite

  steps:
    - name: define variables
      id: define-variables
      shell: bash
      run: |
        echo "----------- Test Define Variables Composite -------------"
        echo "${{ inputs.ACR_NAME }}"
        echo "Detectado Branch --> ${{ github.ref_name }}"
        if [[ "${{ inputs.ACR_NAME }}" == 'xpto' && ${{ github.ref_name}} == 'main' ]]; then
          echo "Detectado ACR Corprate."
          echo "Definido ACR de PRD!"
          echo "ACR_NAME=acrproduction" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.ACR_NAME }}" == 'xpto' && "${{ github.ref_name }}" == 'develop' || "${{ github.ref_name }}" == 'release' ]]; then
          echo "Detectado ACR Corporate."
          echo "Definido ACR de DEV/HML!"
          echo "ACR_NAME=acrdevhml" >> $GITHUB_OUTPUT
        else
          echo "Detectado ACR Other Corp."
          echo "${{ inputs.ACR_NAME }}"
          echo "ACR_NAME=braspagxpto" >> $GITHUB_OUTPUT
        fi