nome: 'Define Variables'
description: 'Define as variáveis necessárias para o workflow do projeto.'

inputs:
  ACR:
    description: 'Valor do ACR'
    default: 'braspagxpto'

runs:
  using: composite

  steps:
    - name: define variables
      id: define-variables
      shell: bash
      run: |
        echo "----------- Test Define Variables Composite -------------"
        echo "${{ inputs.ACR }}"
